import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      padding: 20,
    },
    headerContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 25,
      marginTop: 10,
    },
    backBtn: {
      padding: 8,
      marginRight: 10,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    card: {
      padding: 20,
      borderRadius: 20,
      marginBottom: 15,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      shadowColor: colors.shadow,
    },
    label: {
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 10,
      color: colors.textSecondary,
    },
    currencyRow: {
      flexDirection: "row",
      gap: 12,
    },
    currencyBtn: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    currencyBtnActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    currencyText: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.textSecondary,
    },
    currencyTextActive: {
      color: colors.white,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 15,
      height: 55,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    inputPrefix: {
      fontSize: 20,
      fontWeight: "bold",
      marginRight: 10,
      color: colors.textPrimary,
    },
    mainInput: {
      flex: 1,
      fontSize: 20,
      fontWeight: "bold",
      height: "100%",
      color: colors.textPrimary,
    },
    toggleCard: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    toggleTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    toggleSub: {
      fontSize: 12,
      marginTop: 4,
      color: colors.textSecondary,
    },
    categoriesContainer: {
      marginTop: 10,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 15,
      color: colors.textPrimary,
    },
    catCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: 15,
      borderRadius: 16,
      marginBottom: 10,
      borderWidth: 1,
      gap: 15,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    catInputWrapper: {
      flex: 1,
    },
    inputLabel: {
      fontSize: 10,
      marginBottom: 4,
      color: colors.textSecondary,
    },
    catInput: {
      fontSize: 16,
      fontWeight: "600",
      paddingVertical: 4,
      borderBottomWidth: 1,
      color: colors.textPrimary,
      borderBottomColor: colors.border,
    },
    deleteBtn: {
      padding: 8,
    },
    addBtn: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      padding: 15,
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.primary,
      gap: 8,
    },
    addBtnText: {
      fontWeight: "bold",
      color: colors.primary,
    },
    footer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingTop: 20,
      paddingHorizontal: 20,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 20,
    },
    saveBtn: {
      height: 55,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.primary,
    },
    saveBtnText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "bold",
    },
  });
