import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    topBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 20,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    iconBtn: {
      padding: 10,
      borderRadius: 12,
      elevation: 2,
      backgroundColor: colors.surface,
    },
    walletCard: {
      padding: 25,
      borderRadius: 24,
      marginBottom: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 15,
      elevation: 10,
      height: 180,
      justifyContent: "space-between",
      backgroundColor: colors.primary,
    },
    walletHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    walletBalanceLabel: {
      color: "rgba(255,255,255,0.8)",
      fontSize: 14,
      fontWeight: "600",
    },
    walletBalanceValue: {
      color: colors.white,
      fontSize: 36,
      fontWeight: "bold",
      marginVertical: 5,
    },
    walletMonth: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 12,
    },
    walletFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.2)",
      paddingTop: 15,
    },
    walletStatLabel: {
      color: "rgba(255,255,255,0.7)",
      fontSize: 10,
    },
    walletStatValue: {
      color: colors.white,
      fontSize: 14,
      fontWeight: "bold",
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 15,
      color: colors.textPrimary,
    },
    upcomingBillsScroll: {
      marginHorizontal: -20,
      paddingHorizontal: 20,
    },
    billChip: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 16,
      marginRight: 10,
      borderWidth: 1,
      minWidth: 160,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    iconCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
      backgroundColor: colors.primary + "20",
    },
    billName: {
      fontWeight: "bold",
      fontSize: 14,
      color: colors.textPrimary,
    },
    billDetail: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    categoryRow: {
      padding: 15,
      borderRadius: 16,
      marginBottom: 10,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    categoryHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    catName: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    catVal: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    progressBarBg: {
      height: 6,
      borderRadius: 3,
      overflow: "hidden",
      backgroundColor: colors.background,
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 3,
    },
    txRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 15,
      borderRadius: 16,
      marginBottom: 10,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    txLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    txIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    txDesc: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    txDate: {
      fontSize: 12,
      marginTop: 2,
      color: colors.textSecondary,
    },
    txAmount: {
      fontWeight: "bold",
      fontSize: 16,
    },
    emptyTx: {
      alignItems: "center",
      marginTop: 20,
      opacity: 0.6,
    },
    emptyTxText: {
      color: colors.textMuted,
      marginTop: 5,
    },
    dockContainer: {
      position: "absolute",
      alignSelf: "center",
      flexDirection: "row",
      backgroundColor: colors.surface,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 5,
      gap: 15,
    },
    dockItem: {
      alignItems: "center",
      width: 60,
    },
    dockIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 4,
    },
    dockLabel: {
      fontSize: 10,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    divider: {
      width: 1,
      height: "80%",
      backgroundColor: colors.border,
      alignSelf: "center",
    },
    bottomModal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    bottomModalContent: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 25,
      paddingBottom: 40,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    dragHandleContainer: {
      alignItems: "center",
      marginBottom: 15,
      marginTop: -10,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 10,
      opacity: 0.5,
      backgroundColor: colors.border,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      marginBottom: 5,
      textAlign: "center",
      color: colors.textPrimary,
    },
    modalSub: {
      textAlign: "center",
      marginBottom: 20,
      fontSize: 13,
      color: colors.textSecondary,
    },
    input: {
      borderWidth: 1,
      borderRadius: 12,
      padding: 15,
      marginBottom: 15,
      fontSize: 16,
      borderColor: colors.border,
      backgroundColor: colors.background,
      color: colors.textPrimary,
    },
    catSelectRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 20,
    },
    catChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    catChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    catChipText: {
      color: colors.textSecondary,
      fontWeight: "600",
    },
    catChipTextActive: {
      color: colors.white,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: 20,
      marginTop: 10,
    },
    saveBtn: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    saveBtnText: {
      color: "#fff",
      fontWeight: "bold",
    },
    cancelText: {
      fontWeight: "600",
      color: colors.textSecondary,
    },
  });
