import { StyleSheet } from "react-native";

export const getStyles = (colors) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.85)",
      justifyContent: "center",
      alignItems: "center",
    },
    container: {
      width: "85%",
      padding: 30,
      borderRadius: 30,
      alignItems: "center",
      borderWidth: 1,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      shadowColor: colors.primary,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 30,
    },
    title: {
      fontSize: 22,
      fontWeight: "bold",
      letterSpacing: 1,
      color: colors.textPrimary,
    },
    timerCircle: {
      width: 240,
      height: 240,
      borderRadius: 120,
      borderWidth: 4,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 30,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.6,
      shadowRadius: 15,
      elevation: 10,
      backgroundColor: colors.background,
      borderColor: colors.primary,
      shadowColor: colors.primary,
    },
    timerCircleActive: {
      borderColor: colors.danger,
      shadowColor: colors.danger,
    },
    timerText: {
      fontWeight: "bold",
      fontVariant: ["tabular-nums"],
      textShadowColor: "rgba(0,0,0,0.3)",
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
      color: colors.textPrimary,
      fontSize: 56,
    },
    timerTextLong: {
      fontSize: 42,
    },
    timerTextActive: {
      color: colors.danger,
    },
    statusSubText: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: -5,
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 25,
    },
    inputLabel: {
      color: colors.textSecondary,
      fontWeight: "600",
    },
    input: {
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 15,
      minWidth: 80,
      textAlign: "center",
      marginLeft: 10,
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    row: {
      flexDirection: "column",
      gap: 15,
      width: "100%",
    },
    btn: {
      paddingVertical: 16,
      borderRadius: 16,
      alignItems: "center",
      width: "100%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
      backgroundColor: colors.primary,
    },
    btnActive: {
      backgroundColor: colors.danger,
    },
    closeBtn: {
      backgroundColor: "transparent",
      borderWidth: 1,
      elevation: 0,
      borderColor: colors.textMuted,
    },
    btnText: {
      color: "#fff",
      fontWeight: "bold",
      fontSize: 16,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    closeBtnText: {
      color: colors.textSecondary,
      fontWeight: "bold",
      fontSize: 16,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
  });
