import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    centerContent: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 15,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    groupSelector: {
      marginBottom: 15,
      paddingLeft: 20,
    },
    groupChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      marginRight: 10,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    groupChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    groupChipText: {
      color: colors.textSecondary,
      fontWeight: "600",
    },
    groupChipTextActive: {
      color: colors.white,
      fontWeight: "600",
    },
    addGroupChip: {
      paddingHorizontal: 12,
    },
    memberBadge: {
      marginLeft: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
      backgroundColor: "rgba(255,255,255,0.2)",
    },
    card: {
      borderRadius: 16,
      marginBottom: 15,
      overflow: "hidden",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      shadowColor: colors.shadow,
    },
    authorRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
    },
    authorAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      marginRight: 10,
      justifyContent: "center",
      alignItems: "center",
    },
    authorName: {
      fontWeight: "600",
      fontSize: 14,
      color: colors.textPrimary,
    },
    dateText: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    editBtn: {
      padding: 6,
    },
    postImage: {
      width: "100%",
      height: 200,
    },
    postContent: {
      padding: 12,
    },
    rowBetween: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    topicText: {
      fontSize: 16,
      fontWeight: "bold",
      flex: 1,
      marginRight: 10,
      color: colors.textPrimary,
    },
    textPreview: {
      fontSize: 13,
      marginTop: 6,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 8,
    },
    locText: {
      fontSize: 11,
      marginLeft: 4,
      color: colors.textSecondary,
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 8,
    },
    miniTag: {
      fontSize: 11,
      fontWeight: "600",
    },
    tagBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      marginRight: 6,
      marginTop: 6,
    },
    fab: {
      position: "absolute",
      right: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
    },
    emptyContainer: {
      alignItems: "center",
      marginTop: 50,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "600",
      marginTop: 12,
      color: colors.textPrimary,
    },
    emptySubtitle: {
      fontSize: 14,
      marginTop: 4,
      textAlign: "center",
      color: colors.textSecondary,
    },
    actionButtons: {
      marginTop: 24,
      gap: 12,
    },
    actionBtn: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      gap: 8,
    },
    actionBtnText: {
      color: "#FFF",
      fontWeight: "600",
      fontSize: 15,
    },
    modal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    modalContent: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 20,
      paddingTop: 10,
      maxHeight: "80%",
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    dragHandle: {
      width: 40,
      height: 4,
      backgroundColor: colors.border || "#888",
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 15,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 20,
      color: colors.textPrimary,
    },
    section: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 1,
      marginBottom: 8,
      color: colors.textSecondary,
    },
    inputRow: {
      flexDirection: "row",
      gap: 10,
    },
    input: {
      flex: 1,
      height: 48,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 15,
      fontSize: 15,
      borderColor: colors.border,
      backgroundColor: colors.background,
      color: colors.textPrimary,
    },
    inputBtn: {
      width: 48,
      height: 48,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    groupInfoCard: {
      padding: 15,
      borderRadius: 12,
    },
    groupInfoName: {
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 8,
      color: colors.textPrimary,
    },
    codeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    inviteCode: {
      fontWeight: "bold",
      fontSize: 16,
      letterSpacing: 2,
    },
    membersBtn: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 10,
    },
    memberRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: "rgba(128,128,128,0.2)",
    },
    memberAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    memberName: {
      fontWeight: "600",
      color: colors.textPrimary,
    },
    detailModal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    detailCard: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: "90%",
      paddingTop: 10,
      backgroundColor: colors.surface,
    },
    detailImage: {
      width: "100%",
      height: 300,
    },
    detailBody: {
      padding: 20,
    },
    detailTitle: {
      fontSize: 22,
      fontWeight: "bold",
      flex: 1,
      color: colors.textPrimary,
    },
    detailText: {
      fontSize: 15,
      lineHeight: 24,
      marginTop: 15,
      color: colors.textPrimary,
    },
    closeDetailBtn: {
      position: "absolute",
      top: 20,
      right: 20,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    editDetailBtn: {
      position: "absolute",
      top: 20,
      right: 65,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    reactionBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingBottom: 10,
      paddingTop: 4,
    },
    reactionsLeft: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    reactionBubble: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      gap: 4,
    },
    reactionCount: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    addReactionBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    reactionPicker: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingVertical: 10,
      paddingHorizontal: 15,
      marginHorizontal: 12,
      marginBottom: 10,
      borderRadius: 16,
      borderWidth: 1,
    },
    emojiBtn: {
      padding: 6,
    },
    settingsBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      marginTop: 12,
      borderRadius: 12,
      borderWidth: 1.5,
    },
    transferBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    shareInviteBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      marginTop: 12,
      marginBottom: 8,
      borderRadius: 12,
    },
    divider: {
      height: 1,
      marginVertical: 20,
      marginHorizontal: -20,
    },
  });
