import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerCard: {
      padding: 15,
      paddingBottom: 10,
      borderBottomWidth: 1,
      backgroundColor: colors.surface,
      borderBottomColor: colors.border,
    },
    groupCode: {
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 10,
      fontSize: 11,
      color: colors.textSecondary,
    },
    actionRow: {
      flexDirection: "row",
      gap: 10,
      marginTop: 10,
    },
    actionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
      borderColor: colors.border,
    },
    btnText: {
      fontWeight: "600",
      fontSize: 13,
      color: colors.textPrimary,
    },
    scrollContent: {
      padding: 20,
      paddingBottom: 120,
    },
    sectionHeader: {
      fontSize: 12,
      fontWeight: "bold",
      marginTop: 20,
      marginBottom: 10,
      textTransform: "uppercase",
      color: colors.textSecondary,
    },
    emptyOverview: {
      alignItems: "center",
      marginTop: 30,
    },
    emptyOverviewText: {
      color: colors.textMuted,
      marginTop: 10,
    },
    debtCard: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 15,
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 10,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    debtCardInvolved: {
      borderColor: colors.primary,
      borderWidth: 1,
    },
    debtMemberRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    debtMemberName: {
      marginHorizontal: 10,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    debtCenter: {
      alignItems: "center",
    },
    debtSendsText: {
      fontSize: 10,
      color: colors.textSecondary,
    },
    debtAmount: {
      fontWeight: "bold",
      color: colors.primary,
    },
    avatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarDanger: {
      backgroundColor: colors.danger + "20",
    },
    avatarSuccess: {
      backgroundColor: colors.success + "20",
    },
    avatarPrimary: {
      backgroundColor: colors.primary + "20",
    },
    bigAddMemberBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 15,
      borderRadius: 12,
      marginVertical: 20,
      gap: 10,
      backgroundColor: colors.surfaceHighlight || "#f0f0f0",
      marginTop: 30,
    },
    bigAddMemberText: {
      fontWeight: "bold",
      fontSize: 16,
      color: colors.textPrimary,
    },
    deleteGroupBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 15,
      marginTop: 10,
      marginBottom: 20,
    },
    deleteGroupText: {
      color: colors.danger,
      fontWeight: "bold",
    },
    modalContent: {
      padding: 20,
      borderRadius: 15,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 15,
      textAlign: "center",
      color: colors.textPrimary,
    },
    modalHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitleLeft: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    modalTitleLarge: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    input: {
      height: 50,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      color: colors.textPrimary,
      marginBottom: 15,
    },
    modalSaveBtn: {
      backgroundColor: colors.primary,
      padding: 12,
      borderRadius: 8,
      alignItems: "center",
    },
    modalSaveBtnText: {
      color: "white",
      fontWeight: "bold",
    },
    memberList: {
      maxHeight: 400,
    },
    memberRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    memberNameText: {
      fontSize: 16,
      fontWeight: "500",
      color: colors.textPrimary,
    },
    bottomModal: {
      margin: 0,
      justifyContent: "flex-end",
    },
    spendingSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      height: "60%",
      padding: 20,
    },
    spendingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    spendingAmount: {
      color: colors.primary,
      fontWeight: "bold",
      fontSize: 16,
    },
    historySheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      height: "70%",
      padding: 20,
    },
    historySectionTitle: {
      color: colors.primary,
      fontWeight: "bold",
      marginBottom: 10,
    },
    historyActivityTitle: {
      color: colors.textSecondary,
      fontWeight: "bold",
      marginBottom: 10,
      marginTop: 10,
    },
    historyItem: {
      flexDirection: "row",
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      alignItems: "center",
    },
    historyItemText: {
      fontSize: 14,
      color: colors.textPrimary,
    },
    historyDate: {
      color: colors.textSecondary,
      fontSize: 11,
    },
    historyAmount: {
      color: colors.success,
      fontWeight: "bold",
    },
    activityItem: {
      flexDirection: "row",
      marginBottom: 15,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      paddingBottom: 10,
    },
    activityText: {
      fontSize: 14,
      color: colors.textPrimary,
    },
    activityDate: {
      color: colors.textSecondary,
      fontSize: 11,
      marginTop: 2,
    },
  });
