import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 20,
      backgroundColor: colors.background,
    },
    headerArea: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    headerTitle: {
      letterSpacing: -1,
      color: colors.textPrimary,
    },
    headerSub: {
      fontSize: 14,
      fontWeight: "500",
      marginTop: 4,
      color: colors.textSecondary,
    },
    progressCircle: {
      width: 45,
      height: 45,
      borderRadius: 25,
      backgroundColor: "rgba(255, 215, 0, 0.15)",
      justifyContent: "center",
      alignItems: "center",
    },
    catScroll: {
      gap: 10,
      paddingRight: 20,
    },
    catPill: {
      paddingHorizontal: 16,
      paddingVertical: 6,
      borderRadius: 25,
      borderWidth: 1,
      justifyContent: "center",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    catPillActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    catText: {
      fontWeight: "400",
      fontSize: 13,
      color: colors.textSecondary,
    },
    catTextActive: {
      color: colors.white,
    },
    card: {
      padding: 18,
      borderRadius: 20,
      marginBottom: 12,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      shadowColor: colors.shadow,
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    textContainer: {
      flex: 1,
    },
    itemText: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 6,
      color: colors.textPrimary,
    },
    categoryBadge: {
      alignSelf: "flex-start",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    categoryText: {
      fontSize: 10,
      fontWeight: "bold",
    },
    fab: {
      position: "absolute",
      right: 25,
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 10,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
    },
    emptyContainer: {
      alignItems: "center",
      marginTop: 60,
      opacity: 0.7,
    },
    emptyText: {
      textAlign: "center",
      marginTop: 15,
      fontSize: 16,
      color: colors.textSecondary,
    },
    modalContainer: {
      justifyContent: "flex-end",
      margin: 0,
    },
    modalContent: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 25,
      borderWidth: 1,
      paddingBottom: 40,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    dragHandleContainer: {
      alignItems: "center",
      marginBottom: 15,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 10,
      opacity: 0.5,
      backgroundColor: colors.border,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      marginBottom: 20,
      color: colors.textPrimary,
    },
    input: {
      borderWidth: 1,
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      fontSize: 16,
      backgroundColor: colors.background,
      color: colors.textPrimary,
      borderColor: colors.border,
    },
    label: {
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 12,
      color: colors.textSecondary,
    },
    catWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 30,
    },
    catChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 12,
      borderWidth: 1,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    catChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    catChipText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    catChipTextActive: {
      color: colors.white,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: 20,
    },
    saveBtn: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 14,
      backgroundColor: colors.primary,
    },
    saveBtnText: {
      color: "#fff",
      fontWeight: "bold",
      fontSize: 15,
    },
  });
