import { Platform, StatusBar, StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === "android" ? StatusBar.currentHeight + 20 : 60,
    },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 20,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    viewToggle: {
      flexDirection: "row",
      borderRadius: 16,
      borderWidth: 1,
      padding: 4,
      gap: 5,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    toggleBtn: {
      padding: 8,
      borderRadius: 12,
    },
    toggleBtnActive: {
      backgroundColor: colors.primary,
    },
    filterContainer: {
      marginBottom: 20,
      paddingHorizontal: 20,
    },
    filterListContent: {
      paddingRight: 20,
    },
    filterChip: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      marginRight: 10,
      borderWidth: 1,
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterChipInactive: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    filterChipText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    filterChipTextActive: {
      color: colors.white,
    },
    // Card View
    card: {
      borderRadius: 20,
      marginBottom: 16,
      overflow: "hidden",
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    imageContainer: {
      height: 140,
      width: "100%",
      position: "relative",
    },
    cardImage: {
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    placeholderImage: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.surfaceHighlight,
    },
    dateBadge: {
      position: "absolute",
      top: 10,
      right: 10,
      backgroundColor: "rgba(0,0,0,0.6)",
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 10,
    },
    dateText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "bold",
    },
    statusDot: {
      position: "absolute",
      top: 10,
      left: 10,
      width: 22,
      height: 22,
      borderRadius: 11,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 4,
    },
    cardContent: {
      padding: 15,
    },
    rowBetween: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    rowStart: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 5,
    },
    topicText: {
      fontSize: 18,
      fontWeight: "bold",
      flex: 1,
      color: colors.textPrimary,
    },
    locText: {
      fontSize: 12,
      marginLeft: 4,
      color: colors.textSecondary,
    },
    tagRow: {
      flexDirection: "row",
      marginTop: 8,
      gap: 10,
    },
    miniTag: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.primary,
    },
    // Compact View
    compactRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 10,
      borderRadius: 16,
      marginBottom: 10,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    compactImage: {
      width: 50,
      height: 50,
      borderRadius: 12,
      marginRight: 15,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.surfaceHighlight,
    },
    compactDate: {
      fontSize: 10,
      marginBottom: 2,
      color: colors.textSecondary,
    },
    compactTopic: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    // Month Folder View
    folderCard: {
      borderRadius: 24,
      padding: 20,
      marginBottom: 15,
      height: 140,
      flexDirection: "row",
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    folderContent: {
      flex: 1,
      justifyContent: "space-between",
    },
    folderTitle: {
      color: "#fff",
      fontSize: 22,
      fontWeight: "bold",
    },
    folderCount: {
      color: "rgba(255,255,255,0.8)",
      fontSize: 14,
      fontWeight: "bold",
    },
    folderPreview: {
      width: 100,
      height: "100%",
      position: "relative",
    },
    folderThumb: {
      width: 60,
      height: 70,
      borderRadius: 10,
      position: "absolute",
      top: 20,
      borderWidth: 2,
      borderColor: "#fff",
    },
    subHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 15,
    },
    subHeaderBack: {
      flexDirection: "row",
      alignItems: "center",
    },
    backText: {
      color: colors.primary,
      fontWeight: "bold",
      marginLeft: 5,
    },
    subTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    // FAB
    fab: {
      position: "absolute",
      right: 30,
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 10,
      shadowColor: colors.primary,
      backgroundColor: colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
    },
    // Detail Modal Styles
    detailModal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    detailCard: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      height: "90%",
      overflow: "hidden",
      width: "100%",
      backgroundColor: colors.surface,
    },
    dragHandleContainer: {
      alignItems: "center",
      paddingVertical: 10,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 10,
      opacity: 0.5,
      backgroundColor: colors.border,
    },
    detailImage: {
      width: "100%",
      height: 350,
      resizeMode: "cover",
    },
    detailBody: {
      padding: 25,
      paddingBottom: 60,
    },
    detailDate: {
      fontSize: 14,
      fontWeight: "600",
      opacity: 0.7,
      color: colors.textSecondary,
    },
    detailTitle: {
      fontSize: 28,
      fontWeight: "bold",
      marginTop: 10,
      marginBottom: 5,
      color: colors.textPrimary,
    },
    detailLocRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 5,
      marginVertical: 10,
    },
    detailLocText: {
      color: colors.textSecondary,
      marginLeft: 5,
    },
    detailTagsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginVertical: 10,
    },
    detailTagBadge: {
      backgroundColor: colors.surfaceHighlight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
    detailTagText: {
      color: colors.textPrimary,
      fontSize: 12,
    },
    detailText: {
      fontSize: 18,
      lineHeight: 28,
      opacity: 0.9,
      color: colors.textPrimary,
    },
    closeDetailBtn: {
      position: "absolute",
      top: 20,
      right: 20,
      backgroundColor: "rgba(0,0,0,0.5)",
      padding: 10,
      borderRadius: 20,
    },
    editDetailBtn: {
      position: "absolute",
      bottom: 20,
      right: 20,
      backgroundColor: "#2563EB",
      padding: 15,
      borderRadius: 30,
      elevation: 5,
    },
    // Full screen image modal
    fullScreenContainer: {
      flex: 1,
      backgroundColor: "#000",
      justifyContent: "center",
    },
    fullScreenCloseBtn: {
      position: "absolute",
      top: 40,
      right: 20,
      zIndex: 10,
      padding: 10,
      backgroundColor: "rgba(0,0,0,0.5)",
      borderRadius: 20,
    },
    fullScreenImage: {
      width: "100%",
      height: "100%",
      resizeMode: "contain",
    },
  });
