import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerContainer: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 20,
    },
    headerTitle: {
      fontWeight: "bold",
      marginBottom: 15,
      color: colors.textPrimary,
    },
    segmentContainer: {
      flexDirection: "row",
      borderRadius: 30,
      padding: 4,
      backgroundColor: colors.surface,
    },
    segmentBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 25,
      alignItems: "center",
    },
    segmentBtnActive: {
      backgroundColor: colors.primary,
    },
    segmentText: {
      fontWeight: "700",
      fontSize: 14,
      color: colors.textSecondary,
    },
    segmentTextActive: {
      color: colors.white,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
      color: colors.textPrimary,
    },
    emptyState: {
      alignItems: "center",
      marginTop: 40,
      opacity: 0.7,
    },
    emptyText: {
      fontSize: 14,
      marginTop: 10,
      color: colors.textMuted,
    },
    fab: {
      position: "absolute",
      right: 20,
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 5,
      shadowOpacity: 0.4,
      shadowOffset: { width: 0, height: 4 },
      backgroundColor: colors.primary,
    },
    dateHeader: {
      textAlign: "center",
      marginBottom: 15,
      fontWeight: "bold",
      fontSize: 16,
      textTransform: "uppercase",
      letterSpacing: 1,
      color: colors.primary,
    },
    quickActions: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 20,
    },
    quickBtn: {
      flex: 1,
      borderWidth: 1,
      paddingVertical: 12,
      borderRadius: 16,
      alignItems: "center",
    },
    card: {
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 15,
    },
    subName: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    subDetail: {
      fontSize: 12,
      marginTop: 4,
      color: colors.textSecondary,
    },
    percentBadge: {
      alignItems: "flex-end",
    },
    percentText: {
      fontSize: 20,
      fontWeight: "bold",
    },
    percentLabel: {
      fontSize: 10,
      color: colors.textSecondary,
    },
    progressContainer: {
      padding: 12,
      borderRadius: 16,
      marginBottom: 15,
      backgroundColor: colors.background,
    },
    progressHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    progressLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    progressValue: {
      fontSize: 12,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    barRow: {
      flexDirection: "row",
      gap: 4,
      height: 6,
      marginTop: 8,
    },
    barSegment: {
      flex: 1,
      borderRadius: 4,
    },
    btnRow: {
      flexDirection: "row",
      gap: 12,
    },
    actionBtn: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 12,
      borderRadius: 16,
      gap: 8,
    },
    resetBtn: {
      alignSelf: "center",
      marginTop: 10,
    },
    resetText: {
      textDecorationLine: "underline",
      fontSize: 12,
      color: colors.textMuted,
    },
    manageCard: {
      borderRadius: 24,
      padding: 20,
      backgroundColor: colors.surface,
    },
    manageHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 15,
    },
    tagCloud: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    tag: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 20,
      gap: 8,
      borderWidth: 1,
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    tagText: {
      fontWeight: "500",
      color: colors.textPrimary,
    },
    dayRow: {
      marginBottom: 15,
      borderBottomWidth: 1,
      paddingBottom: 10,
      borderBottomColor: colors.border,
    },
    dayHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    dayTitle: {
      fontWeight: "bold",
      color: colors.primary,
    },
    addLink: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    classList: {
      paddingLeft: 10,
    },
    classItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 5,
    },
    classText: {
      fontSize: 14,
      color: colors.textPrimary,
    },
    countBadge: {
      fontSize: 12,
      fontWeight: "bold",
      color: colors.textSecondary,
    },
    bottomModal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    bottomModalContent: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingBottom: 40,
      borderWidth: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    dragHandleContainer: {
      alignItems: "center",
      marginBottom: 20,
      marginTop: -10,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 10,
      opacity: 0.5,
      backgroundColor: colors.border,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      marginBottom: 20,
      color: colors.textPrimary,
    },
    input: {
      padding: 16,
      borderRadius: 12,
      marginBottom: 20,
      borderWidth: 1,
      backgroundColor: colors.background,
      color: colors.textPrimary,
      borderColor: colors.border,
    },
    label: {
      marginBottom: 10,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    weekSelector: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    dayCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
      borderColor: colors.border,
    },
    dayCircleActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    dayCircleText: {
      fontSize: 12,
      fontWeight: "bold",
      color: colors.textSecondary,
    },
    dayCircleTextActive: {
      color: colors.white,
    },
    counterList: {
      marginBottom: 20,
    },
    counterRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
      paddingHorizontal: 5,
    },
    counterControls: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    counterBtn: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: 20,
      marginTop: 10,
    },
    saveBtn: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: colors.primary,
    },
    saveBtnText: {
      fontWeight: "bold",
      color: colors.white,
    },
    cancelText: {
      fontWeight: "600",
      color: colors.textMuted,
    },
    calendar: {
      marginBottom: 20,
      borderRadius: 16,
    },
    tabContent: {
      flex: 1,
      paddingHorizontal: 20,
    },
    settingsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    settingsTextContainer: {
      flex: 1,
    },
    settingsLabel: {
      color: colors.textPrimary,
      fontWeight: "600",
      fontSize: 16,
    },
    settingsSubLabel: {
      color: colors.textSecondary,
      fontSize: 12,
    },
    settingsInputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    settingsInputWrap: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderRadius: 12,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    settingsInput: {
      color: colors.textPrimary,
      fontWeight: "bold",
      fontSize: 16,
      paddingVertical: 8,
      width: 40,
      textAlign: "center",
    },
    settingsUnit: {
      color: colors.textSecondary,
      fontWeight: "bold",
    },
    settingsSaveBtn: {
      backgroundColor: colors.primary,
      padding: 10,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    quickBtnPresent: {
      borderColor: colors.success,
      backgroundColor: colors.success + "10",
    },
    quickBtnAbsent: {
      borderColor: colors.danger,
      backgroundColor: colors.danger + "10",
    },
    quickBtnTextPresent: {
      color: colors.success,
      fontWeight: "bold",
    },
    quickBtnTextAbsent: {
      color: colors.danger,
      fontWeight: "bold",
    },
    actionBtnPresent: {
      backgroundColor: colors.success + "20",
      borderColor: colors.success,
      borderWidth: 1,
    },
    actionBtnAbsent: {
      backgroundColor: colors.danger + "20",
      borderColor: colors.danger,
      borderWidth: 1,
    },
    actionBtnTextPresent: {
      color: colors.success,
      fontWeight: "bold",
    },
    actionBtnTextAbsent: {
      color: colors.danger,
      fontWeight: "bold",
    },
    scheduleClassRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    freeDayText: {
      color: colors.textMuted,
      fontSize: 12,
      fontStyle: "italic",
    },
  });
