import { StyleSheet } from "react-native";

export default (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      padding: 24,
      paddingBottom: 50,
      justifyContent: "center",
      minHeight: "100%",
    },
    header: {
      alignItems: "center",
      marginBottom: 40,
      marginTop: 20,
    },
    iconCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
      backgroundColor: colors.surfaceHighlight,
    },
    title: {
      fontSize: 32,
      fontWeight: "800",
      marginBottom: 8,
      textAlign: "center",
      color: colors.textPrimary,
    },
    subtitle: {
      fontSize: 16,
      textAlign: "center",
      maxWidth: "80%",
      color: colors.textSecondary,
    },
    section: { marginBottom: 25 },
    label: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 15,
      marginLeft: 4,
      color: colors.textPrimary,
    },
    input: {
      padding: 18,
      borderRadius: 16,
      fontSize: 16,
      borderWidth: 1,
      backgroundColor: colors.surface,
      color: colors.textPrimary,
      borderColor: colors.border,
    },
    row: { flexDirection: "row", gap: 15 },
    card: {
      flex: 1,
      padding: 20,
      borderRadius: 20,
      alignItems: "center",
      borderWidth: 2,
      justifyContent: "center",
      height: 120,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    cardActive: {
      backgroundColor: colors.surfaceHighlight,
      borderColor: colors.primary,
      shadowColor: colors.primary,
    },
    cardText: {
      fontSize: 14,
      fontWeight: "bold",
      marginTop: 10,
    },
    toggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      borderRadius: 16,
      justifyContent: "space-between",
      backgroundColor: colors.surface,
    },
    toggleLabel: { fontSize: 16, fontWeight: "bold", color: colors.textPrimary },
    toggleSub: { fontSize: 12, marginTop: 2, color: colors.textSecondary },
    button: {
      paddingVertical: 18,
      borderRadius: 20,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 8,
    },
    buttonText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  });
